### ISSUE TITLE
install.sh don't work

### ISSUE THREAD

**Issue by Attila972** [mattbryson/momentum-desktop-images#1]
Hello,
It seems the shell script ./install.sh don't work normally

**Comment by mattbryson** [comment]
Hmm, what version of OSX are your running?  Maybe the LaunchAgents folder is optional, and the script would need to create it if its not there?   

You could try creating the folder and then running the script...

`mkdir ~/Library/LaunchAgents`

**Comment by Attila972** [comment]
Thanks You, It's work now.

Yes You should add the cmd to create the folder in case its not there. 
(OSX v10.11.6)

Otherwise, It is possible to download the pictures in the Momentum history (settings cog/Backgrounds/History) ?

**Comment by mattbryson** [comment]
I have added the check, I have also changed the install script to automate a lot of the set up now, so you just need to enter the client ID when it asks, and it will do the rest, including updating the OSX  desktops settings for you.
