### ISSUE TITLE
Does X-Momentum-Version needed?

### ISSUE THREAD

**Issue by a110605** [mattbryson/momentum-desktop-images#3]
Hi ,
It seems that you use momentum API to get background image back.
I have entered my client-ID and get two pictures back. But it is not the current image used on my chrome new tab.
I wonder if **X-Momentum-Version**(in sync_momentum.py Line #19) is needed?
or it just gets two random pictures back?

Thanks.

AndyLee

**Comment by mattbryson** [comment]
It gets the daily pictures.  The chrome plugin will be caching previous days pictures, as well as a list of hardcoded default images.

If you would like your current ones, you can find their location using the chrome inspector, and then copy them in to the  momentum-desktop-images/pictures folder.
